name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: taski_db
          POSTGRES_USER: taski_user
          POSTGRES_PASSWORD: taski_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: taski_db
      POSTGRES_USER: taski_user
      POSTGRES_PASSWORD: taski_password
      DB_HOST: db
      DB_PORT: 5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          cd backend
          python manage.py migrate
          python manage.py test

