name: Deploy to VPS

on:
  push:
    branches: [main]          
  workflow_run:               
    workflows: ["CD-build"]  
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}           
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: |
            docker-compose.yml
            .env
            nginx/default.conf
          target: /home/yc-user/taski-docker    
          rm: false

    
      - name: Run docker compose up on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/taski-docker
            docker compose pull
            docker compose up -d --remove-orphans
